/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.lgangloff.web.api;


import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Data;

@Data
@JsonInclude(value = Include.NON_NULL)
public class ApiResponseCollection<T> {
    private String apiVersion;
    private ApiDataCollection<T> data;
    private ApiError error;

    public ApiResponseCollection(String apiVersion, Class<T> clazz, List<T> items){
        this.apiVersion = apiVersion;
        data = new ApiDataCollection<>(clazz, items);
    }
}
