/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.lgangloff.web.api;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Data;

@Data
@JsonInclude(value = Include.NON_NULL)
public class ApiResponse<T> {
    private String apiVersion;
    private ApiData<T> data;
    private ApiError error;

    public ApiResponse(String apiVersion, T entity){
        this.apiVersion = apiVersion;
        data = new ApiData<>(entity);
    }
}
